sudo: false

language: node_js
node_js:
  - 10

before_install:
  - npm install codecov.io

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - master
